image: docker-ci-helper:utils

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  STACK_NAME: mdEditor

stages:
  - build
  - deploy

build:
  stage: build
  # build any valid version
  script:
    - source /root/utils
    - env
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

# template for performing a deployment (the steps are identical regardless of environment)
.deploy_template: &deploy_common
  stage: deploy
  when: manual
  dependencies:
    - build

deploy:test:
  variables:
    DOCKER_HOST: "ssh://test2"
  <<: *deploy_common
  script:
    - source /root/utils
    - env
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker-compose -f stack.yml config
    - docker stack deploy --with-registry-auth -c stack.yml $STACK_NAME
    - docker stack ps $STACK_NAME
  environment:
    name: test
    url: https://mdeditor.djcase.com

